# Generated by Django 3.0.2 on 2020-01-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='emial',
            field=models.CharField(default='NULL', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='NULL', max_length=30),
            preserve_default=False,
        ),
    ]
